### ISSUE TITLE
Please install the "units" package

### ISSUE THREAD

**Issue by rdbnchr** [skykooler/ulauncher-conversion#2]
Whenever i try to use the extension 
I have this message 
Please install the "units" package
I tried installing the units package for python but it doesn't seem to work

**Comment by VovanR** [comment]
It uses [this](https://www.gnu.org/software/units/) program.
In Ubuntu: `sudo apt install units`.
After installation complete you need to exit Ulauncher program and start it again.

**Comment by ben2talk** [comment]
This is fairly useful - but Instructions would be nice... I wouldn't give a can opener to a toddler and walk away - and then wonder why it's unused by an ungrateful toddler.

And one reason people hate Arch Linux forums is that people there shout at you 'RTFM' whether you are capable of understanding it or not (please excuse the inflammatory reference...).

Ubuntu isn't the only OS either. For Arch it's 'pacman -S units', but when I needed currency conversion I went back to using 'g' instead of 'convert'. It wouldn't work!!!

To find out why it doesn't work, one needs to go to the terminal (for example, converting Thai Baht - and what answers can you get - these can be listed with 'tab' autocomplete to decide what to type for what you want.

**Comment by sheksushant** [comment]
Please add this one this information to readme.md

**Comment by purezen** [comment]
I am using Pop 20.04.

I am still getting the message even after running `sudo apt install units` which worked fine.

**Comment by FunMLG** [comment]
I had this message too. I installed the units package (`sudo pacman -S units`) but now it won't convert what I want. It loads in the void
